# Python 3.10 resmi Docker görüntüsünü kullanıyoruz
FROM python:3.10-slim

# Çalışma dizinini ayarla
WORKDIR /app

# Proje dosyalarını konteynıra kopyala
COPY . .

# Gerekli Python bağımlılıklarını yükle
RUN pip install --no-cache-dir -r requirements.txt

# Uygulama başlatma komutu (FastAPI için)
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8080"]

# Veya Flask için
# CMD ["python", "main.py"]
